#!/bin/sh

[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/.cargo/bin" ] ; then
    PATH="$HOME/.cargo/bin:$PATH"
fi

# Proxy
export NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com,mx"
export HTTP_PROXY="http://localhost:7890"
export HTTPS_PROXY=$HTTP_PROXY

export EDITOR="nvim"
# QT Appearance
export QT_QPA_PLATFORMTHEME=gtk2

# Electron app use trash-cli as trash manager
export ELECTRON_TRASH=trash-cli
# Need install xdg-desktop-portal
# export GTK_USE_PORTAL=1
