# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="meet"

plugins=(cargo
    git
    pyenv
    nvm
    sudo
    z
    zsh-autosuggestions
    zsh-syntax-highlighting)


source $ZSH/oh-my-zsh.sh

# User configuration
export TERM=xterm-256color
export LS_COLORS="di=1;34:ln=35:so=33:pi=33:ex=1;32:bd=34:cd=32:su=32:sg=32:tw=1;34:ow=1;34"

alias ez='emacs --daemon'
alias es=$'emacsclient -e "(save-buffers-kill-emacs)"'
alias e='emacs -nw'
alias ec='emacsclient -t --alternate-editor=""'
alias vim='nvim'
